baseURL = "https://blog.wangc.org/"
defaultContentLanguage = "en"
hasCJKLanguage = true
languageCode = "en"
paginate = 10
theme = "hugo-theme-texify"
title = "Meaningless"

disqusShortname = ""
googleAnalytics = "UA-127207962-1"
pygmentsUseClasses = true

[author]
name = "chenwang0"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  identifier = "post"
  name = "Post"
  url = "/"
  weight = 1
[[menu.main]]
  identifier = "archives"
  name = "Archives"
  url = "/post/"
  weight = 2
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 3
[permalinks]
  "/" = "/:year/:month/:filename/"
[params]
  customCSS = ["css/custom.css"]
  dateFormat = "2006-01-02"
  description = "an example site for hugo theme TeXify"
  enableFullRSS = true
  enableHanEmph = true
  enableMathjax = true
  favicon = "/favicon.ico"
  footnote = "Follow me on <a class=link href=https://github.com/wchen9>GitHub</a>, <a class=link href=https://twitter.com/queensferryme>Twitter</a> or <a class=link href=/index.xml>RSS</a> | <a class=link href=https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh target=_blank rel=noopener>CC BY-NC-SA 4.0</a>"
  keywords = ["hugo", "latex", "theme"]

# see https://utteranc.es for installation guide
[params.utterances]
  enable = true
  repo = "wchen9/blog"
  issue_term = "pathname"
  label = "Comment"
  theme = "github-light"
