baseURL = "https://blog.wangc.org"
title = "Meaningless"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
hasCJKLanguage = true

[params]
description = "Maybe a software engineer"
dark = "auto"
highlight = true

[[menu.main]]
identifier = "about"
name = "about"
title = "about"
url = "/about/"
weight = 30

[permalinks]
posts = "/:filename/"

[markup.goldmark.renderer]
# Allow HTML in Markdown
unsafe = true

[markup.tableOfContents]
ordered = true
